name: Page
on:
  push:
    paths-ignore:
      - worker/**

jobs:
  page:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key:
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{
            hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - run: npm install
        env:
          GITHUB_NPM_TOKEN: ${{ secrets.GH_NPM_PACKAGE_READ_TOKEN }}
      - run: npx @cloudflare/next-on-pages --experimental-minify
        env:
          NODE_VERSION: 18

      - id: publish
        name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CF_PAGES_TOKEN }}
          accountId: "4f59a390b9f139a4a82b757edd3c71dd"
          projectName: supabasejwt
          directory: .vercel/output/static
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
